import type { Metadata } from "next";
import Link from "next/link";
import { InfoShell } from "../components/info-shell";
import { AdSlot } from "../components/ad-slot";
export const metadata: Metadata = { title: "How to convert Markdown to images", description: "Learn how to import Markdown, add local images, create multi-page carousels, and export PNG, JPEG, or WebP files with MarkdownPic.", alternates: { canonical: "/help" } };
export default function Help() {
  return <InfoShell><h1>Markdown to image, without the extra steps.</h1><p>Write or paste Markdown, choose a canvas, and export a readable image. The editor runs in your browser. You do not need an account.</p>
    <p className="guide-pointer">Working on something specific? The <Link href="/guides">guides</Link> cover <Link href="/guides/long-image">high-resolution long images</Link>, <Link href="/guides/markdown-table-to-image">tables</Link>, <Link href="/guides/mermaid-to-png">Mermaid diagrams</Link>, <Link href="/guides/latex-math-to-image">math</Link>, <Link href="/guides/code-to-image">code</Link> and <Link href="/guides/markdown-carousel">carousels</Link>.</p>
    <h2>Your first image</h2><ol><li>Paste your text into the editor, use <strong>Open file</strong> for a Markdown file, or choose a template.</li><li>Open <strong>Customize</strong> to set the size, colors, typeface, and padding. Auto height grows with your content.</li><li>Choose <strong>Export PNG</strong>. The result screen shows the actual exported file. Use Options for JPEG, WebP, or a different resolution.</li></ol>
    <h2>On a phone</h2><p>Use the Edit and Preview tabs to move between your words and your image. The export controls stay at the bottom. After export, use <strong>Share image</strong> when your browser supports file sharing, or <strong>Open image</strong> and your browser’s save action. A multi-page export downloads as a ZIP; you can also save each image individually from the result screen.</p>
    <h2>Supported Markdown</h2><p>Headings, bold and italic text, links, lists, task lists, block quotes, tables, and fenced code blocks are supported. Math uses KaTeX. Diagrams use Mermaid. Raw HTML and embedded scripts are not rendered.</p><pre><code>{"# A useful idea\n\nA sentence with **emphasis**.\n\n> One clear takeaway.\n\n- First detail\n- Second detail"}</code></pre>
    <h3>Math and diagrams</h3><p>Use <code>$...$</code> for inline math and <code>$$...$$</code> for a displayed formula. Use a fenced code block with the language <code>mermaid</code> for a diagram. The Formula and Flowchart templates give you editable examples.</p>
    <h2>Add images without unreadable source</h2><p>Choose <strong>Add image</strong>, paste an image from your clipboard, or drag an image into the editor. PNG, JPEG, and WebP are supported, up to 12 MB and 32 megapixels each. Images are stored in this browser; the Markdown contains a short local reference.</p><p>Remote image URLs need to allow cross-origin loading. If an image is blocked, download it yourself when permitted and insert the local file. Remote images contact their source server. A relative path such as <code>./photo.png</code> in an imported Markdown file does not contain the image; insert that image separately.</p>
    <h2>Create multiple pages</h2><p>Select <strong>Pages</strong> to edit each page individually. Add, reorder, or remove pages using the page strip. In a Markdown file, put <code>{"<!-- page -->"}</code> on its own line to mark a page break. Markers inside code blocks are treated as code.</p><p><strong>Auto split</strong> measures real content against a fixed canvas. It keeps headings with their content and can divide long paragraphs, lists, and tables at safe boundaries. A code block, image, formula, or diagram that is taller than a page needs a taller size or smaller content. If automatic pagination cannot complete, your original remains unchanged. A project supports up to 20 pages.</p><p>Customize can change the project default or just the current page. A page-specific style stays in place when you change the default; use Reset this page to remove that override.</p>
    <AdSlot slot="inline" /><h2>Understand output size</h2><p>The preview header shows the actual output dimensions at the selected resolution. At 2×, Square is 1080 × 1080, Portrait is 1080 × 1350, Story is 1080 × 1920, and Landscape is 1200 × 630 pixels. Auto height is 1200 pixels wide at 2× and grows to fit the content.</p><p>Preview zoom only changes the on-screen view. Image text size changes the exported layout. Editor text size changes only the input area. Very large exports are stopped before downloading; lower the resolution or split the content if needed.</p>
    <h2>Keep your work safe</h2><p>My projects stores drafts in this browser, not in an online account. Templates and imported files create a new project. Undo and redo cover the current editing session. Clearing site data, private browsing, device loss, or browser storage eviction can remove local drafts.</p><p>Choose <strong>Back up current project</strong> to download a <code>.mdpic</code> file containing Markdown, page styles, and local images. Restore it on another device using Open file. This is the portable, editable copy. A plain <code>.md</code> download contains text but not local image bytes.</p><p>If the same project changes in another tab, saving pauses to prevent an accidental overwrite. Open the latest saved version or save your version as a copy.</p>
    <h2>If export fails</h2><ul><li><strong>Content too tall:</strong> use Auto height, Auto split, or a smaller image text size.</li><li><strong>Content too wide:</strong> simplify a table, formula, or diagram, or choose a wider canvas.</li><li><strong>Missing image:</strong> replace it with a supported local file or restore a complete project backup.</li><li><strong>Diagram error:</strong> check Mermaid syntax or start with the Flowchart template.</li><li><strong>No clipboard or share support:</strong> use Download again or Open image.</li><li><strong>Local save failed:</strong> back up before leaving. Free browser storage and retry.</li></ul>
    <h2>Keyboard shortcuts</h2><p><kbd>Ctrl / ⌘ + Enter</kbd> exports the image. <kbd>Ctrl / ⌘ + Z</kbd> undoes a change; add Shift to redo. All major controls can be reached with Tab.</p>
    <AdSlot slot="inline" />
  </InfoShell>;
}
