import { exampleMarkdown, PAGE_BREAK_MARKER, themeLook, type FontFamily, type ThemeId } from "./studio-model.ts";

export interface Template { id: string; name: string; description: string; markdown: string; theme: ThemeId; size: string; font?: FontFamily; accent?: string }

export const templates: Template[] = [
  { id: "note", name: "A clear idea", description: "A headline, useful detail, and one takeaway.", markdown: exampleMarkdown, theme: "editorial", size: "long" },
  { id: "quote", name: "Quote", description: "A short thought with an attribution.", markdown: '# Clarity is a form of respect.\n\nGive the reader the conclusion, the reason, and enough space to think.\n\n— **Your name**', theme: "ink", size: "square" },
  { id: "release", name: "Release note", description: "What shipped, what changed, and what is next.", markdown: '# A better way to work\n\n## What’s new\n\n- A simpler first step\n- Clearer feedback when something goes wrong\n- Less time adjusting, more time creating\n\n**Available today.**\n\nReplace this example with your own update.', theme: "plum", size: "portrait" },
  { id: "steps", name: "Step-by-step", description: "An easy-to-follow process.", markdown: '# From rough idea to useful post\n\n1. Start with the conclusion.\n2. Add one piece of evidence.\n3. Remove anything that repeats the point.\n4. End with a clear next action.\n\n> Structure makes ideas easier to share.', theme: "harbor", size: "portrait" },
  { id: "table", name: "Comparison", description: "A readable table with context.", markdown: '# Choose the right format\n\n| Format | Best for | Trade-off |\n| --- | --- | --- |\n| PNG | Text and diagrams | Larger file |\n| JPEG | Photos | Lossy compression |\n| WebP | Compact images | Check platform support |\n\n**Tip:** keep your Markdown source for future edits.', theme: "mono", size: "long" },
  { id: "code", name: "Code + context", description: "Explain a snippet, not just the syntax.", markdown: '# Small, readable functions\n\nGive each function one job and a name that explains it.\n\n~~~javascript\nfunction readingMinutes(words) {\n  return Math.max(1, Math.ceil(words / 200));\n}\n~~~\n\nThe result is always **at least one minute**.\n\n> Code travels better with context.', theme: "terminal", size: "long" },
  { id: "diagram", name: "Flowchart", description: "A Mermaid diagram that stays editable.", markdown: '# A simple publishing flow\n\n~~~mermaid\nflowchart TD\n  A[Write] --> B[Preview]\n  B --> C{Ready?}\n  C -->|Yes| D[Export]\n  C -->|Not yet| A\n~~~\n\nKeep the source. Improve the explanation.', theme: "mist", size: "long" },
  { id: "math", name: "Formula", description: "Math with a clear explanation.", markdown: '# Small improvements compound\n\n$$\nA = P(1 + r)^t\n$$\n\n- **P** — starting value\n- **r** — rate of improvement\n- **t** — time\n\nSmall changes become meaningful when they accumulate.', theme: "linen", size: "square" },
  { id: "carousel", name: "Three-page story", description: "A beginning, the reasoning, and a next step.", markdown: `# One idea, three clear frames.\n\nStart with the conclusion your reader should remember.\n\n${PAGE_BREAK_MARKER}\n\n# Show the reasoning\n\n- One useful piece of evidence\n- One concrete example\n- No repeated explanation\n\n${PAGE_BREAK_MARKER}\n\n# Make it actionable\n\nGive the reader one clear next step.\n\n> Good carousels feel like progress, not fragments.`, theme: "rose", size: "portrait" },
];

/** A template opens in its theme's full look (accent and typeface), unless it names its own. */
export const templateDesign = <T extends { theme: ThemeId; presetId: string; fontFamily: FontFamily; accent: string }>(base: T, template: Template): T =>
  ({ ...base, ...themeLook(template.theme), presetId: template.size, ...(template.font ? { fontFamily: template.font } : {}), ...(template.accent ? { accent: template.accent } : {}) });
